use crate::person::{Person, PersonId};
use crate::person::ratings::*;

pub fn get_team_0() -> Vec<Person> {
    let player_0_0: Person = Person {
        name: "STARCENTER".to_string(),
        person_id: PersonId("starcenter_c_team0".to_string()),
        age: 20,
        team: Some("team0".to_string()),
        personality: Personality {
            loyalty: 30,
            work_ethic: 73,
            dog: 72,
            adaptability: 37,
            creativity: 58,
            intelligence: 51,
        },
        intangibles: IntangibleRatings {
            ball_handle: 40,
            burst: 68,
            def_awareness: 55,
            fluidity: 67,
            hands: 50,
            height: 71,
            off_awareness: 31,
            pass_accuracy: 45,
            shot_form: 29,
            lateral: 5,
            speed: 65,
            strength: 58,
            wingspan: 60,
            touch: 47,
        },
    };

    let player_1_0: Person = Person {
        name: "AllAroundWing".to_string(),
        person_id: PersonId("allaroundwing_sf_team0".to_string()),
        age: 21,
        team: Some("team0".to_string()),
        personality: Personality {
            loyalty: 30,
            work_ethic: 20,
            dog: 50,
            adaptability: 68,
            creativity: 69,
            intelligence: 64,
        },
        intangibles: IntangibleRatings {
            ball_handle: 44,
            burst: 28,
            def_awareness: 44,
            fluidity: 46,
            hands: 38,
            height: 59,
            off_awareness: 21,
            pass_accuracy: 63,
            shot_form: 41,
            lateral: 53,
            speed: 33,
            strength: 46,
            wingspan: 59,
            touch: 52,
        },
    };

    let player_2_0: Person = Person {
        name: "LowUsgGuard".to_string(),
        person_id: PersonId("lowusgguard_team0".to_string()),
        age: 22,
        team: Some("team0".to_string()),
        personality: Personality {
            loyalty: 30,
            work_ethic: 20,
            dog: 32,
            adaptability: 65,
            creativity: 4,
            intelligence: 38,
        },
        intangibles: IntangibleRatings {
            ball_handle: 33,
            burst: 67,
            def_awareness: 65,
            fluidity: 65,
            hands: 30,
            height: 43,
            off_awareness: 59,
            pass_accuracy: 29,
            shot_form: 70,
            lateral: 47,
            speed: 70,
            strength: 27,
            wingspan: 47,
            touch: 56,
        },
    };

    let player_3_0: Person = Person {
        name: "Defensive SF".to_string(),
        person_id: PersonId("defensivesf_team0".to_string()),
        age: 23,
        team: Some("team0".to_string()),
        personality: Personality {
            loyalty: 30,
            work_ethic: 20,
            dog: 26,
            adaptability: 69,
            creativity: 25,
            intelligence: 57,
        },
        intangibles: IntangibleRatings {
            ball_handle: 42,
            burst: 53,
            def_awareness: 75,
            fluidity: 49,
            hands: 56,
            height: 50,
            off_awareness: 63,
            pass_accuracy: 19,
            shot_form: 44,
            lateral: 51,
            speed: 55,
            strength: 15,
            wingspan: 20,
            touch: 31,
        },
    };

    let player_4_0: Person = Person {
        name: "IntelligentPG".to_string(),
        person_id: PersonId("intelligentpg_team0".to_string()),
        age: 24,
        team: Some("team0".to_string()),
        personality: Personality {
            loyalty: 30,
            work_ethic: 41,
            dog: 50,
            adaptability: 60,
            creativity: 59,
            intelligence: 68,
        },
        intangibles: IntangibleRatings {
            ball_handle: 50,
            burst: 16,
            def_awareness: 77,
            fluidity: 14,
            hands: 10,
            height: 43,
            off_awareness: 58,
            pass_accuracy: 80,
            shot_form: 75,
            lateral: 75,
            speed: 6,
            strength: 55,
            wingspan: 19,
            touch: 66,
        },
    };

    let team_0 = vec![player_4_0, player_3_0, player_2_0, player_1_0, player_0_0];
    team_0
}
pub fn get_team_1() -> Vec<Person> {
    let player_0_1: Person = Person {
        name: "STAR_PG".to_string(),
        person_id: PersonId("star_pg_team1".to_string()),
        age: 20,
        team: Some("team1".to_string()),
        personality: Personality {
            loyalty: 30,
            work_ethic: 20,
            dog: 27,
            adaptability: 55,
            creativity: 54,
            intelligence: 47,
        },
        intangibles: IntangibleRatings {
            ball_handle: 68,
            burst: 95,
            def_awareness: 46,
            fluidity: 91,
            hands: 68,
            height: 21,
            off_awareness: 49,
            pass_accuracy: 48,
            shot_form: 64,
            lateral: 54,
            speed: 100,
            strength: 23,
            wingspan: 42,
            touch: 71,
        },
    };
    let player_1_1: Person = Person {
        name: "Sharpshooter_SG".to_string(),
        person_id: PersonId("sharpshooter_sg_team1".to_string()),
        age: 21,
        team: Some("team1".to_string()),
        personality: Personality {
            loyalty: 30,
            work_ethic: 49,
            dog: 71,
            adaptability: 40,
            creativity: 63,
            intelligence: 52,
        },
        intangibles: IntangibleRatings {
            ball_handle: 53,
            burst: 32,
            def_awareness: 54,
            fluidity: 32,
            hands: 74,
            height: 39,
            off_awareness: 58,
            pass_accuracy: 29,
            shot_form: 91,
            lateral: 43,
            speed: 40,
            strength: 47,
            wingspan: 59,
            touch: 86,
        },
    };

    let player_2_1: Person = Person {
        name: "SLASHING_WING_SF".to_string(),
        person_id: PersonId("slashingwing_sf_team1".to_string()),
        age: 22,
        team: Some("team1".to_string()),
        personality: Personality {
            loyalty: 30,
            work_ethic: 57,
            dog: 77,
            adaptability: 27,
            creativity: 41,
            intelligence: 42,
        },
        intangibles: IntangibleRatings {
            ball_handle: 42,
            burst: 45,
            def_awareness: 59,
            fluidity: 45,
            hands: 22,
            height: 57,
            off_awareness: 60,
            pass_accuracy: 36,
            shot_form: 54,
            lateral: 23,
            speed: 43,
            strength: 34,
            wingspan: 20,
            touch: 61,
        },
    };

    let player_3_1: Person = Person {
        name: "DefenseLiable_PF".to_string(),
        person_id: PersonId("dliable_pf_team1".to_string()),
        age: 23,
        team: Some("team1".to_string()),
        personality: Personality {
            loyalty: 42,
            work_ethic: 20,
            dog: 27,
            adaptability: 69,
            creativity: 54,
            intelligence: 66,
        },
        intangibles: IntangibleRatings {
            ball_handle: 42,
            burst: 2,
            def_awareness: 70,
            fluidity: 13,
            hands: 35,
            height: 57,
            off_awareness: 41,
            pass_accuracy: 43,
            shot_form: 51,
            lateral: 35,
            speed: 9,
            strength: 73,
            wingspan: 52,
            touch: 41,
        },
    };

    let player_4_1: Person = Person {
        name: "RIMRUNNER_C".to_string(),
        person_id: PersonId("rimrunner_c_team1".to_string()),
        age: 24,
        team: Some("team1".to_string()),
        personality: Personality {
            loyalty: 58,
            work_ethic: 60,
            dog: 49,
            adaptability: 65,
            creativity: 35,
            intelligence: 60,
        },
        intangibles: IntangibleRatings {
            ball_handle: 23,
            burst: 15,
            def_awareness: 62,
            fluidity: 10,
            hands: 15,
            height: 80,
            off_awareness: 34,
            pass_accuracy: 47,
            shot_form: 26,
            lateral: 3,
            speed: 9,
            strength: 5,
            wingspan: 48,
            touch: 15,
        },
    };

    let team_1 = vec![player_4_1, player_3_1, player_2_1, player_1_1, player_0_1];

    team_1
}
